export const companyLinks = [
  ['/about', 'Tentang PPP'], ['/company-profile', 'Company Profile'], ['/customers', 'Pelanggan Kami'],
  ['/contact', 'Hubungi Kami'], ['/careers', 'Karier'], ['/terms', 'Syarat & Ketentuan'], ['/privacy', 'Kebijakan Privasi'],
] as const;
export const formPages = [
  { slug: 'quotation', title: 'Request for Quotation', intro: 'Sampaikan daftar barang, spesifikasi, dan jumlah yang Anda perlukan.', field: 'Daftar produk & spesifikasi', placeholder: 'Contoh: kontaktor, merek, tipe, tegangan, jumlah, dan target pengiriman.', note: 'Sudah menemukan produk di katalog? Gunakan keranjang untuk menyusun permintaan penawaran.', link: '/cart', linkText: 'Buka keranjang' },
  { slug: 'sales-visit', title: 'Kunjungan Sales', intro: 'Diskusikan kebutuhan pengadaan perusahaan Anda bersama tim kami.', field: 'Agenda & lokasi kunjungan', placeholder: 'Alamat perusahaan, topik diskusi, dan pilihan waktu kunjungan.', note: 'Jadwal dan cakupan kunjungan akan dikonfirmasi oleh tim sales.' },
  { slug: 'service-visit', title: 'Kunjungan Service', intro: 'Konsultasikan kendala peralatan dan kebutuhan pemeriksaan teknis.', field: 'Peralatan & kendala', placeholder: 'Merek, tipe, gejala kerusakan, lokasi, dan waktu yang diharapkan.', note: 'Ketersediaan teknisi, cakupan pekerjaan, dan biaya perlu dikonfirmasi terlebih dahulu.' },
  { slug: 'payment-terms', title: 'Pengajuan Tempo', intro: 'Diskusikan kebutuhan termin pembayaran untuk pengadaan perusahaan.', field: 'Kebutuhan termin pembayaran', placeholder: 'Jenis usaha, perkiraan kebutuhan pembelian, dan termin yang diajukan.', note: 'Pengajuan akan ditinjau oleh tim PPP. Pengisian formulir tidak berarti persetujuan fasilitas tempo.' },
  { slug: 'support-letter', title: 'Surat Dukungan', intro: 'Ajukan kebutuhan dokumen pendukung untuk pengadaan atau proyek.', field: 'Detail proyek & dokumen', placeholder: 'Nama proyek, instansi, produk, jenis surat, dan tenggat dokumen.', note: 'Penerbitan surat bergantung pada kelengkapan data dan konfirmasi pihak terkait.' },
  { slug: 'partner', title: 'Daftar Mitra / Supplier', intro: 'Perkenalkan produk dan layanan perusahaan Anda kepada tim PPP.', field: 'Profil usaha & penawaran kerja sama', placeholder: 'Bidang usaha, merek atau produk, wilayah layanan, dan tautan katalog.', note: 'Tim kami akan meninjau kesesuaian penawaran dengan kebutuhan pengadaan.' },
] as const;
export const formLinks = formPages.map(p => [`/forms/${p.slug}`, p.title] as const);
export const guidePages = [
  { slug: 'payment', title: 'Metode Pembayaran', intro: 'Pastikan detail pembayaran sesuai dengan penawaran yang Anda terima.', sections: [['Konfirmasi invoice', 'Periksa nama perusahaan, rincian barang, jumlah, dan nilai tagihan sebelum melakukan pembayaran.'], ['Informasi rekening', 'Minta informasi rekening pembayaran melalui kontak resmi PPP. Metode pembayaran yang tersedia dikonfirmasi pada penawaran atau invoice.'], ['Konfirmasi pembayaran', 'Sampaikan nomor invoice dan bukti pembayaran kepada tim sales agar pembayaran dapat dicocokkan dengan pesanan.']] },
  { slug: 'shipping', title: 'Metode Pengiriman', intro: 'Koordinasikan pengiriman sesuai jenis barang dan tujuan proyek Anda.', sections: [['Siapkan alamat lengkap', 'Cantumkan alamat tujuan, kode pos, nama penerima, nomor telepon, dan ketentuan penerimaan barang di lokasi.'], ['Diskusikan pilihan pengiriman', 'Pilihan ekspedisi, pengemasan, biaya, dan estimasi waktu dikonfirmasi berdasarkan ukuran barang serta tujuan pengiriman.'], ['Periksa saat menerima', 'Cocokkan jumlah dan kondisi barang dengan dokumen pengiriman. Simpan foto kemasan dan label bila ada ketidaksesuaian.']] },
  { slug: 'shopping', title: 'Panduan Belanja', intro: 'Dari pencarian komponen sampai konfirmasi kebutuhan pembelian.', sections: [['01 · Temukan produk', 'Cari berdasarkan nama, merek, atau kode barang. Periksa tipe dan spesifikasi agar sesuai dengan aplikasi peralatan Anda.'], ['02 · Susun kebutuhan', 'Tambahkan barang ke keranjang dan sesuaikan jumlah. Untuk barang yang belum ada di katalog, gunakan formulir Request for Quotation.'], ['03 · Minta penawaran', 'Lengkapi kontak dan detail kebutuhan. Tim sales akan mengonfirmasi harga, stok, waktu pengadaan, serta pengiriman sebelum pemesanan.']] },
  { slug: 'quotation', title: 'Panduan Quotation', intro: 'Informasi yang lengkap membantu tim kami menyiapkan penawaran yang tepat.', sections: [['Data barang', 'Tuliskan merek, part number, spesifikasi, satuan, dan jumlah. Untuk penggantian komponen, siapkan foto nameplate atau datasheet untuk dibagikan kepada sales.'], ['Data pengadaan', 'Sertakan nama perusahaan, lokasi pengiriman, target waktu, serta kebutuhan dokumen. Sampaikan bila produk alternatif dapat dipertimbangkan.'], ['Tinjau penawaran', 'Periksa kesesuaian barang, masa berlaku penawaran, pajak, ongkos kirim, termin pembayaran, dan estimasi pengadaan bersama tim sales.']] },
  { slug: 'returns', title: 'Pengembalian Barang & Dana', intro: 'Hubungi tim kami untuk pemeriksaan apabila pesanan tidak sesuai.', sections: [['Siapkan informasi pesanan', 'Sertakan nomor invoice, tanggal penerimaan, tipe barang, jumlah, serta foto atau video yang menunjukkan masalah.'], ['Minta arahan pengembalian', 'Diskusikan keluhan sebelum mengirimkan barang kembali. Simpan kemasan, kelengkapan, dan dokumen pembelian untuk proses pemeriksaan.'], ['Konfirmasi penyelesaian', 'Kelayakan retur, penggantian, biaya pengiriman, dan pengembalian dana ditentukan setelah pemeriksaan dan mengacu pada kesepakatan transaksi.']] },
  { slug: 'warranty', title: 'Informasi Garansi', intro: 'Cek cakupan garansi untuk produk yang Anda perlukan sebelum memesan.', sections: [['Cakupan per produk', 'Ketentuan dan periode garansi dapat berbeda menurut merek, tipe, dan pemasok. Minta detail tertulis pada penawaran.'], ['Dokumen klaim', 'Siapkan invoice, nomor seri, foto produk, dan penjelasan kendala. Jelaskan kondisi penggunaan untuk membantu pemeriksaan.'], ['Proses pemeriksaan', 'Tim sales akan membantu mengarahkan proses klaim sesuai ketentuan produk. Hasil dan waktu penyelesaian mengikuti konfirmasi pihak terkait.']] },
  { slug: 'pickup', title: 'Panduan Pick Up', intro: 'Atur pengambilan barang dengan tim sales sebelum datang.', sections: [['Konfirmasi kesiapan barang', 'Hubungi tim sales dengan nomor pesanan dan pastikan barang sudah siap diambil.'], ['Jadwalkan pengambilan', 'Konfirmasikan lokasi, jam pengambilan, nama pengambil, dan jenis kendaraan bila barang berukuran besar.'], ['Periksa kelengkapan', 'Bawa referensi pesanan dan cocokkan barang serta dokumen bersama petugas saat serah terima.']] },
] as const;
export const guideLinks = [...guidePages.map(p => [`/help/${p.slug}`, p.title] as const), ['/tracking', 'Tracking Order']] as const;
