import { useEffect, useState, FormEvent } from 'react';
import { Link, NavLink, Outlet, useLocation, useNavigate } from 'react-router-dom';
import { Search, ShoppingCart, UserRound, Phone, ArrowUpRight, Menu, X, Mail, MapPin, MessageCircle, Clock, ArrowRight } from 'lucide-react';
import { useStore } from '@/contexts/StoreContext';
import { useAuth } from '@/contexts/AuthContext';
import { companyLinks, formLinks, guideLinks } from '@/lib/site-pages';

export function StoreLogo() { return <Link to="/" className="store-logo" aria-label="Prima Putra Perkasa — beranda"><span className="logo-mark">P<span>P</span></span><span>PRIMA PUTRA<strong>PERKASA<span>INDUSTRIAL SUPPLY</span></strong></span></Link>; }
export default function StoreLayout() {
  const { cart, demo } = useStore(); const { user } = useAuth();
  const navigate = useNavigate(); const location = useLocation();
  const [search, setSearch] = useState(''); const [menu, setMenu] = useState(false);
  useEffect(() => { setMenu(false); if (location.hash) { requestAnimationFrame(() => document.getElementById(location.hash.slice(1))?.scrollIntoView()); } else { window.scrollTo({ top: 0, behavior: 'instant' }); } }, [location.pathname, location.hash]);
  useEffect(() => { setSearch(new URLSearchParams(location.search).get('q') || ''); }, [location.search]);
  const submit = (event: FormEvent) => { event.preventDefault(); navigate(`/products${search.trim() ? `?q=${encodeURIComponent(search.trim())}` : ''}`); };
  return <div className="storefront"><a href="#main-content" className="skip-link">Lewati ke konten</a>
    <div className="utility-bar"><div className="store-container"><span>Mitra pengadaan elektrikal & mekanikal sejak 2003</span><a href="tel:+62216246441"><Phone size={12} /> (021) 6246441</a><Link to="/contact">Bantuan pengadaan <ArrowUpRight size={12} /></Link></div></div>
    <header className="store-header"><div className="store-container header-main"><StoreLogo /><form className="store-search" role="search" onSubmit={submit}><Search size={20} /><input type="search" placeholder="Cari produk, merek, atau kode barang..." aria-label="Cari produk, merek, atau kode barang" value={search} onChange={e => setSearch(e.target.value)} maxLength={150} /><button type="submit" aria-label="Cari">Cari</button></form><Link to="/account" className="header-action"><UserRound size={22} /><span>{user ? 'Akun saya' : 'Masuk / Daftar'}</span></Link><Link to="/cart" className="header-action cart-action" aria-label={`Keranjang, ${cart.reduce((n,l) => n+l.quantity,0)} barang`}><ShoppingCart size={23} /><span>Keranjang</span>{cart.length > 0 && <b>{cart.reduce((n,l) => n+l.quantity,0)}</b>}</Link><button className="mobile-menu" aria-label="Menu navigasi" aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</button></div>
      <nav className={`store-nav ${menu ? 'open' : ''}`} aria-label="Navigasi utama" onClick={event => { if ((event.target as HTMLElement).closest("a")) setMenu(false); }}><div className="store-container"><NavLink to="/products" className="category-nav"><Menu size={17} /> Semua produk</NavLink><NavLink to="/" end>Beranda</NavLink><NavLink to="/brands">Merek</NavLink><NavLink to="/about">Tentang kami</NavLink><NavLink to="/help">Pusat bantuan</NavLink><NavLink to="/contact">Kontak</NavLink><Link to="/forms/quotation" className="nav-quote">Permintaan penawaran <ArrowUpRight size={15} /></Link></div></nav>
    </header>
    {demo && <div className="demo-notice">Pratinjau katalog contoh · Produk belum merupakan penawaran jual. Pengiriman permintaan dinonaktifkan.</div>}
    <main id="main-content" tabIndex={-1}><Outlet /></main>
    <section className="footer-contact-strip"><div className="store-container"><div><span className="eyebrow">KAMI SIAP MEMBANTU</span><h2>Ada kebutuhan untuk proyek Anda?</h2><p>Diskusikan spesifikasi dan kebutuhan pengadaan bersama tim PPP.</p></div><Link className="store-button" to="/forms/quotation">Minta penawaran <ArrowRight size={17} /></Link></div></section>
    <footer className="store-footer expanded-footer"><div className="store-container footer-directory"><div className="footer-company"><StoreLogo /><h3>CV Prima Putra Perkasa</h3><p>General Supplier Electrical & Mechanical.<br />Mitra pengadaan industri sejak 2003.</p><h3>Kunjungi Kami</h3><p className="footer-detail"><MapPin size={17} /><span>Lindeteves Trade Centre Lt. 2 Blok B20 No. 6,<br />Jl. Hayam Wuruk No. 127, Jakarta Barat</span></p><h3>Layanan Informasi</h3><a href="tel:+62216246441"><Phone size={16} />(021) 6246441</a><a href="mailto:sales@primaputraperkasa.com"><Mail size={16} /><span>sales@primaputraperkasa.com</span></a><a href="https://wa.me/6287885572522" target="_blank" rel="noopener noreferrer"><MessageCircle size={16} />0878-8557-2522</a><h3>Jam Operasional</h3><p className="footer-detail"><Clock size={16} /><span>Senin–Jumat: 08.00–17.00<br />Sabtu: 08.00–12.00</span></p></div><div><h3>Tentang Kami</h3>{companyLinks.map(([path, label]) => <Link key={path} to={path}>{label}</Link>)}<h3 className="footer-subheading">Katalog & Akun</h3><Link to="/products">Semua Produk</Link><Link to="/brands">Merek Pilihan</Link><Link to="/account">Permintaan Saya</Link></div><div><h3>Formulir</h3>{formLinks.map(([path, label]) => <Link key={path} to={path}>{label}</Link>)}<div className="footer-service-box"><MessageCircle size={24} /><strong>Butuh komponen khusus?</strong><p>Kirim tipe dan spesifikasi kepada tim kami.</p><Link to="/contact">Konsultasikan kebutuhan <ArrowUpRight size={14} /></Link></div></div><div><h3>Bantuan & Panduan</h3>{guideLinks.map(([path, label]) => <Link key={path} to={path}>{label}</Link>)}<Link to="/help" className="footer-all-help">Pusat Bantuan <ArrowRight size={14} /></Link><h3 className="footer-subheading">Pembayaran & Pengiriman</h3><p>Metode pembayaran dan opsi pengiriman dikonfirmasi sesuai penawaran Anda.</p></div></div><div className="store-container footer-bottom"><span>© {new Date().getFullYear()} CV Prima Putra Perkasa.</span><span>Electrical & Mechanical · Since 2003</span></div></footer>
    <a className="floating-whatsapp" href="https://wa.me/6287885572522" target="_blank" rel="noopener noreferrer" aria-label="Hubungi PPP melalui WhatsApp"><MessageCircle size={27} /><span>Chat dengan kami</span></a>
  </div>;
}
