import { Link } from 'react-router-dom';
import { CheckCircle2, ArrowRight, MapPin, Phone, Mail, Clock, ArrowUpRight } from 'lucide-react';
import { useLanguage } from '@/contexts/LanguageContext';
import { useCatalogFacets } from '@/hooks/useCatalog';
import { Breadcrumb, CatalogState } from '@/components/store/StoreUI';
import hero from '@/assets/hero-industrial.jpg';

export function AboutPage() {
  const { t, language, setLanguage } = useLanguage();
  return <><div className="store-container"><Breadcrumb current="Tentang kami" /></div><section className="about-hero"><div className="store-container"><span className="eyebrow light">CV PRIMA PUTRA PERKASA · EST. 2003</span><h1>Tentang Prima Putra Perkasa</h1><p>General Supplier Electrical & Mechanical<br />untuk industri manufaktur dan kontraktor.</p></div><img src={hero} alt="Lingkungan fasilitas industri" /></section><section className="store-container about-story"><div><span className="eyebrow">TENTANG KAMI</span><h2>{t('buildingTrust')}</h2><div className="language-buttons"><button aria-pressed={language === 'id'} onClick={() => setLanguage('id')}>Indonesia</button><button aria-pressed={language === 'en'} onClick={() => setLanguage('en')}>English</button></div></div><div><p>{t('aboutDesc1')}</p><p>{t('aboutDesc2')}</p>{['authorizedDistributor','extensiveInventory','competitivePricing','expertConsultation'].map(k => <div className="about-benefit" key={k}><CheckCircle2 size={19} />{t(k)}</div>)}</div></section><div className="store-container about-numbers"><div><strong>2003</strong><span>Tahun berdiri</span></div><div><strong>20+</strong><span>Tahun pengalaman</span></div><div><strong>Jakarta</strong><span>Basis layanan kami</span></div></div><section className="store-container about-cta"><span className="eyebrow">MARI BEKERJA SAMA</span><h2>Kebutuhan Anda,<br />prioritas kami.</h2><p>Komponen rutin, kebutuhan proyek, hingga barang yang sulit dicari. Ceritakan kebutuhan Anda kepada tim kami.</p><Link to="/contact" className="store-button">Hubungi tim kami <ArrowRight size={17} /></Link></section></>;
}
export function ContactPage() {
  return <div className="store-container page-space"><Breadcrumb current="Kontak" /><div className="page-heading"><span className="eyebrow">KAMI SIAP MEMBANTU</span><h1>Kontak dan permintaan penawaran</h1><p>Konsultasi produk, permintaan penawaran, dan dukungan pengadaan.</p></div><div className="contact-grid"><div className="contact-panel"><h2>Terhubung dengan tim sales</h2><p>Untuk daftar produk yang sudah Anda pilih, ajukan penawaran melalui keranjang. Untuk kebutuhan khusus, hubungi kami secara langsung. Siapkan nama produk, merek atau part number, spesifikasi, satuan, jumlah, tujuan pengiriman, dan target waktu. Foto nameplate atau datasheet dapat membantu konfirmasi komponen.</p><a className="store-button" href="https://wa.me/6287885572522" target="_blank" rel="noopener noreferrer">Buka WhatsApp sales <ArrowUpRight size={17} /></a><Link className="store-button secondary" to="/cart">Buka keranjang <ArrowRight size={17} /></Link><small>Pesan baru terkirim setelah Anda menekan kirim di WhatsApp.</small></div><div className="contact-details"><div><Phone /><span><strong>Telepon</strong><a href="tel:+62216246441">(021) 6246441</a></span></div><div><Mail /><span><strong>Email</strong><a href="mailto:sales@primaputraperkasa.com">sales@primaputraperkasa.com</a></span></div><div><MapPin /><span><strong>Alamat</strong>Lindeteves Trade Centre Lt. 2 Blok B20 No. 6,<br />Jl. Hayam Wuruk No. 127, Jakarta Barat</span></div><div><Clock /><span><strong>Jam operasional</strong>Senin–Jumat: 08.00–17.00<br />Sabtu: 08.00–12.00</span></div></div></div></div>;
}
export function BrandsPage() {
  const catalog = useCatalogFacets();
  const brands = catalog.data?.brands ?? [], loading = catalog.isLoading, error = catalog.isError;
  return <div className="store-container page-space"><Breadcrumb current="Merek" /><div className="page-heading"><span className="eyebrow">JELAJAHI KATALOG</span><h1>Temukan merek pilihan Anda.</h1><p>Komponen dari berbagai merek untuk kebutuhan elektrikal dan mekanikal.</p></div><CatalogState loading={loading} error={error} reload={() => void catalog.refetch()} />{!loading && !error && <div className="brand-grid">{brands.map(({ name: brand, count }) => <Link key={brand} to={`/products?brand=${encodeURIComponent(brand!)}`}><strong>{brand}</strong><span>{count} produk <ArrowUpRight size={17} /></span></Link>)}</div>}{!loading && !error && !brands.length && <p>Daftar merek sedang dipersiapkan. <Link to="/contact">Hubungi sales.</Link></p>}</div>;
}
