import { FormEvent, useState } from 'react';
import { Link, NavLink, useLocation } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, BookOpen, Building2, ClipboardList, Download, Factory, FileText, Headphones, MessageCircle, Search, Truck, Wrench } from 'lucide-react';
import { Breadcrumb } from '@/components/store/StoreUI';
import { companyLinks, formLinks, formPages, guideLinks, guidePages } from '@/lib/site-pages';
import hero from '@/assets/hero-industrial.jpg';

export function InformationPage({ kind }: { kind: 'company' | 'guide' | 'form' }) {
  const { pathname } = useLocation();
  const slug = pathname.split('/').pop();
  const form = formPages.find(p => p.slug === slug);
  const guide = guidePages.find(p => p.slug === slug);
  const links = kind === 'guide' ? guideLinks : kind === 'form' ? formLinks : companyLinks;
  const title = kind === 'form' ? form?.title : kind === 'guide' ? guide?.title : companyLinks.find(([path]) => path === pathname)?.[1];
  return <div className="store-container page-space"><Breadcrumb current={title || 'Informasi'} /><div className="info-layout"><aside className="info-sidebar"><span className="eyebrow">PRIMA PUTRA PERKASA</span><h2>{kind === 'guide' ? 'Bantuan & Panduan' : kind === 'form' ? 'Formulir Layanan' : 'Tentang Kami'}</h2><nav aria-label="Navigasi informasi">{links.map(([path, label]) => <NavLink key={path} to={path}>{label}<ArrowRight size={14} /></NavLink>)}</nav><div className="info-sidebar-help"><Headphones size={25} /><h3>Perlu bantuan?</h3><p>Tim kami siap mendampingi kebutuhan pengadaan Anda.</p><Link to="/contact">Hubungi tim PPP <ArrowUpRight size={14} /></Link></div></aside><article className="info-content" key={pathname}><div className="page-heading"><span className="eyebrow">{kind === 'guide' ? 'PENGADAAN JADI LEBIH MUDAH' : kind === 'form' ? 'TERHUBUNG DENGAN TIM KAMI' : 'KENALI KAMI LEBIH DEKAT'}</span><h1>{title}</h1>{(form || guide) && <p>{form?.intro || guide?.intro}</p>}</div>{kind === 'form' && form ? <RequestForm config={form} /> : kind === 'guide' && guide ? <><div className="guide-sections">{guide.sections.map(([heading, body], i) => <section key={heading}><span className="step-number">0{i + 1}</span><div><h2>{heading}</h2><p>{body}</p></div></section>)}</div><div className="info-callout"><BookOpen size={25} /><div><h3>Masih ada yang ingin ditanyakan?</h3><p>Sampaikan kebutuhan spesifik Anda kepada tim sales.</p></div><Link to="/contact" className="store-button secondary">Hubungi kami <ArrowRight size={15} /></Link></div></> : <CompanyContent slug={slug || ''} />}</article></div></div>;
}

function RequestForm({ config }: { config: typeof formPages[number] }) {
  const [message, setMessage] = useState('');
  function prepare(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const values = ['name', 'company', 'phone', 'details'].map(key => String(data.get(key) || '').trim());
    if (values.some(value => !value)) return;
    setMessage(`Halo tim PPP, saya ingin mengajukan ${config.title}.\n\nNama: ${values[0]}\nPerusahaan: ${values[1]}\nTelepon: ${values[2]}\nEmail: ${String(data.get('email') || '').trim()}\n\n${config.field}:\n${values[3]}`);
  }
  return <><p className="service-note">{config.note} {'link' in config && <Link to={config.link}>{config.linkText} →</Link>}</p><form className="service-form" onSubmit={prepare} onChange={() => setMessage('')}><h2>Detail permintaan Anda</h2><p>Kolom bertanda * wajib diisi.</p><div className="form-grid"><label>Nama lengkap *<input name="name" autoComplete="name" required maxLength={100} pattern=".*\S.*" /></label><label>Nama perusahaan *<input name="company" autoComplete="organization" required maxLength={150} pattern=".*\S.*" /></label><label>Nomor telepon / WhatsApp *<input name="phone" type="tel" autoComplete="tel" required pattern="[+0-9() .-]{8,25}" maxLength={25} /></label><label>Email<input name="email" type="email" autoComplete="email" maxLength={150} /></label></div><label>{config.field} *<textarea name="details" rows={6} required maxLength={2000} placeholder={config.placeholder} /></label><p className="muted">Data dipakai untuk menindaklanjuti permintaan Anda. <Link to="/privacy">Informasi privasi</Link></p><button className="store-button" type="submit">Siapkan pesan <ArrowRight size={16} /></button><small>Periksa pesan terlebih dahulu, lalu kirim melalui WhatsApp.</small></form>{message && <div className="message-preview" role="status"><h2>Pesan siap ditinjau</h2><p>Permintaan belum terkirim. Buka WhatsApp, lalu tekan kirim untuk menghubungi tim PPP.</p><pre>{message}</pre><a className="store-button" href={`https://wa.me/6287885572522?text=${encodeURIComponent(message)}`} target="_blank" rel="noopener noreferrer">Lanjutkan ke WhatsApp <ArrowUpRight size={16} /></a></div>}</>;
}


function CompanyContent({ slug }: { slug: string }) {
  if (slug === 'company-profile') return <><div className="profile-banner" style={{ backgroundImage: `linear-gradient(90deg,#203238ed,#20323888),url(${hero})` }}><span className="eyebrow light">GENERAL SUPPLIER · EST. 2003</span><h2>Partner untuk<br />kebutuhan industri Anda.</h2><p>Electrical & Mechanical</p></div><div className="editorial-copy"><h2>CV Prima Putra Perkasa</h2><p>Didirikan pada tahun 2003, PPP bergerak di bidang pengadaan kebutuhan elektrikal dan mekanikal untuk industri manufaktur dan kontraktor. Kami membantu pencarian komponen rutin, kebutuhan proyek, serta barang custom atau yang sulit ditemukan.</p><p>Kualitas, keaslian produk, dan kecepatan pengadaan menjadi perhatian kami dalam mendampingi kebutuhan pelanggan.</p></div><div className="info-callout"><FileText size={30} /><div><h3>Company Profile PPP</h3><p>Kenali perusahaan dan lingkup produk kami melalui booklet.</p></div><a className="store-button" href="/documents/company-profile-ppp.pdf" download>Unduh PDF <Download size={16} /></a></div><div className="editorial-copy"><h2>Visi kami</h2><p>Menjadi perusahaan General Supplier terdepan di Indonesia yang mengutamakan kebutuhan dan kepuasan pelanggan.</p><h2>Misi kami</h2><ul className="profile-list"><li>Menyediakan produk mekanikal dan listrik berkualitas dengan harga kompetitif.</li><li>Memberikan layanan purna jual yang cepat dan responsif.</li><li>Mengembangkan sistem kerja yang sederhana dan efektif.</li></ul><h2>Lingkup pengadaan</h2><p>Elektrikal, perlengkapan industri dan mekanikal, pipa dan fitting, cat, perkakas, material konstruksi, serta safety dan PPE.</p></div><Link className="text-button" to="/about">Baca lebih lanjut tentang PPP →</Link></>;
  if (slug === 'customers') return <><p className="info-intro">Mendukung kebutuhan elektrikal dan mekanikal untuk operasional, pemeliharaan, serta proyek industri.</p><h2 className="customer-sector-title">Mendampingi berbagai kebutuhan industri</h2><div className="sector-grid">{[[Factory, 'Industri Manufaktur', 'Komponen pendukung mesin produksi dan kebutuhan operasional pabrik.'], [Building2, 'Kontraktor & Proyek', 'Pengadaan komponen sesuai spesifikasi dan jadwal kebutuhan proyek.'], [Wrench, 'Maintenance & Engineering', 'Pencarian spare part pengganti dan kebutuhan pemeliharaan peralatan.'], [Truck, 'Pengadaan Perusahaan', 'Koordinasi daftar kebutuhan, spesifikasi, dan penawaran dalam satu alur.']].map(([Icon, title, desc]) => { const Mark = Icon as typeof Factory; return <div key={String(title)}><Mark size={30} strokeWidth={1.4} /><h2>{String(title)}</h2><p>{String(desc)}</p></div>; })}</div><div className="info-callout"><Headphones /><div><h3>Mari diskusikan kebutuhan perusahaan Anda</h3><p>Mulai dari daftar barang hingga kebutuhan pengadaan khusus.</p></div><Link to="/forms/sales-visit" className="store-button">Hubungi sales <ArrowRight size={15} /></Link></div></>;
  if (slug === 'careers') return <div className="editorial-copy"><span className="info-icon"><Building2 size={35} /></span><h2>Tumbuh bersama Prima Putra Perkasa</h2><p>Informasi posisi dan proses rekrutmen dapat ditanyakan melalui kontak resmi perusahaan.</p><h3>Informasi lowongan</h3><p>Belum ada lowongan yang ditampilkan di website ini. Hubungi tim kami untuk menanyakan peluang dan kanal pengiriman lamaran yang sesuai.</p><Link className="store-button" to="/contact">Tanyakan peluang karier <ArrowRight size={16} /></Link></div>;
  if (slug === 'terms') return <div className="editorial-copy"><p>Berikut informasi penggunaan katalog dan alur pengadaan melalui PPP. Detail transaksi dikonfirmasi dalam penawaran dan dokumen pemesanan.</p><h2>Katalog & ketersediaan</h2><p>Pastikan tipe, spesifikasi, jumlah, harga, dan ketersediaan barang bersama tim sales sebelum melakukan pemesanan. Informasi katalog membantu pencarian awal kebutuhan Anda.</p><h2>Permintaan & pemesanan</h2><p>Permintaan penawaran merupakan tahap konsultasi pengadaan. Pemesanan diproses setelah rincian barang, pembayaran, dan pengiriman disepakati.</p><h2>Ketentuan transaksi</h2><p>Masa berlaku harga, pajak, biaya kirim, termin pembayaran, garansi, serta ketentuan pembatalan dan retur perlu diperiksa pada penawaran terkait.</p><Link to="/help/quotation" className="text-button">Pelajari panduan quotation →</Link></div>;
  return <div className="editorial-copy"><p>Informasi berikut menjelaskan penggunaan data pada fitur website PPP.</p><h2>Data yang Anda berikan</h2><p>Formulir layanan menggunakan nama, perusahaan, kontak, dan rincian kebutuhan untuk menyusun pesan permintaan. Pesan baru dikirim melalui WhatsApp setelah Anda melanjutkan dan menekan kirim di aplikasi tersebut.</p><h2>Akun & permintaan penawaran</h2><p>Jika Anda menggunakan akun dan mengirim permintaan melalui keranjang, detail akun dan permintaan disimpan untuk proses tindak lanjut pengadaan. Hindari memasukkan kata sandi atau data sensitif pada kolom catatan.</p><h2>Penyimpanan pada perangkat</h2><p>Website menyimpan pilihan keranjang pada browser agar dapat digunakan kembali. Fitur masuk akun menggunakan penyimpanan sesi untuk mempertahankan akses Anda.</p><h2>Layanan pihak ketiga</h2><p>Saat membuka WhatsApp atau layanan eksternal, pemrosesan data pada layanan tersebut mengikuti ketentuan penyedianya.</p><h2>Pertanyaan tentang data</h2><p>Hubungi kontak resmi PPP untuk pertanyaan atau permintaan terkait data yang Anda berikan.</p><Link className="text-button" to="/contact">Hubungi kami →</Link></div>;
}

export function HelpCenter() {
  const [query, setQuery] = useState('');
  const filtered = guidePages.filter(p => `${p.title} ${p.intro}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="store-container page-space"><Breadcrumb current="Pusat Bantuan" /><div className="help-hero"><span className="eyebrow">BANTUAN & PANDUAN</span><h1>Apa yang bisa kami bantu?</h1><p>Temukan panduan untuk setiap langkah pengadaan Anda.</p><label className="help-search"><Search size={20} /><input aria-label="Cari panduan" placeholder="Cari pembayaran, pengiriman, garansi..." value={query} onChange={e => setQuery(e.target.value)} /></label></div><div className="help-grid">{filtered.map((p, i) => <Link to={`/help/${p.slug}`} key={p.slug}><span className="help-card-top"><BookOpen size={24} /><span>0{i + 1}</span></span><h2>{p.title}</h2><p>{p.intro}</p><span className="text-button">Baca panduan <ArrowRight size={15} /></span></Link>)}</div>{!filtered.length && <div className="empty-state"><h2>Panduan tidak ditemukan</h2><p>Coba kata kunci lain atau hubungi tim kami.</p><button className="store-button secondary" onClick={() => setQuery('')}>Tampilkan semua panduan</button></div>}<div className="info-callout"><ClipboardList size={30} /><div><h3>Ingin mengetahui progres pesanan?</h3><p>Gunakan referensi pesanan untuk menghubungi tim sales.</p></div><Link className="store-button" to="/tracking">Tracking Order <ArrowRight size={16} /></Link></div></div>;
}

export function TrackingPage() {
  const [reference, setReference] = useState('');
  const [ready, setReady] = useState(false);
  return <div className="store-container page-space"><Breadcrumb current="Tracking Order" /><div className="tracking-panel"><span className="info-icon"><Truck size={35} /></span><span className="eyebrow">INFORMASI PESANAN</span><h1>Cek progres pengadaan Anda.</h1><p>Masukkan nomor PO, invoice, atau referensi pesanan untuk menyiapkan pertanyaan kepada tim sales.</p><form onSubmit={e => { e.preventDefault(); if (reference.trim()) setReady(true); }}><label>Nomor referensi pesanan<input required maxLength={100} pattern=".*\S.*" value={reference} onChange={e => { setReference(e.target.value); setReady(false); }} placeholder="Contoh: nomor PO atau invoice Anda" /></label><button className="store-button" type="submit">Siapkan pertanyaan <ArrowRight size={16} /></button></form>{ready && <div className="message-preview" role="status"><p>Pertanyaan untuk referensi <strong>{reference.trim()}</strong> siap dikirim. Status akan dikonfirmasi oleh tim sales melalui WhatsApp.</p><a className="store-button" target="_blank" rel="noopener noreferrer" href={`https://wa.me/6287885572522?text=${encodeURIComponent(`Halo tim PPP, mohon informasi progres pesanan dengan referensi: ${reference.trim()}`)}`}><MessageCircle size={17} /> Tanyakan melalui WhatsApp</a></div>}<p className="tracking-note">Untuk permintaan penawaran dari akun Anda, <Link to="/account">lihat riwayat permintaan →</Link></p></div></div>;
}
