import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ShoppingCart, ShieldCheck, MessageCircle } from 'lucide-react';
import { useStore } from '@/contexts/StoreContext';
import { money } from '@/lib/store';
import { Availability, Breadcrumb, CatalogState, ProductImage, Quantity, ProductCard } from '@/components/store/StoreUI';

export default function ProductDetail() {
  const { id } = useParams(); const { products, add, loading, error, demo } = useStore(); const [quantity, setQuantity] = useState(1);
  const product = products.find(p => p.id === id);
  if (loading || error) return <div className="store-container page-space"><CatalogState /></div>;
  if (!product) return <div className="empty-state"><h1>Produk tidak ditemukan</h1><Link to="/products" className="store-button">Kembali ke katalog</Link></div>;
  const related = products.filter(p => p.category === product.category && p.id !== id).slice(0,4);
  return <div className="store-container page-space"><Breadcrumb current={product.name_id} /><div className="product-detail"><ProductImage key={product.id} product={product} large /><div className="product-detail-copy"><Link to={`/products?category=${encodeURIComponent(product.category)}`} className="eyebrow">{product.category}</Link><p className="detail-brand">{product.brand}</p><h1>{product.name_id}</h1><p className="product-sku">Kode produk: {product.sku || product.id}</p><Availability value={product.availability} /><div className="detail-price">{product.price_idr !== null ? money(product.price_idr) : 'Harga berdasarkan penawaran'}<small>{product.price_idr !== null ? ` / ${product.unit}` : 'Hubungi kami untuk harga sesuai kebutuhan Anda.'}</small></div><p className="muted">Harga akhir, pajak, ongkos kirim, dan waktu pengiriman dikonfirmasi dalam penawaran sales.</p><div className="detail-actions"><Quantity value={quantity} onChange={setQuantity} /><button className="store-button" disabled={product.availability === 'unavailable'} onClick={() => add(product.id, quantity)}><ShoppingCart size={18} /> Tambah ke keranjang</button></div><Link to="/cart" className="text-button">Lihat keranjang & ajukan penawaran →</Link><div className="detail-assurance"><ShieldCheck size={19} /><span>Dukungan pemilihan produk dan bantuan klaim garansi.</span></div>{demo && <p className="inline-notice">Produk contoh untuk pratinjau. Belum dapat diajukan sebagai permintaan.</p>}</div></div><section className="product-description"><h2>Informasi produk</h2><p>{product.description_id || 'Hubungi tim sales untuk informasi teknis lengkap produk ini.'}</p><h3>Spesifikasi</h3>{Object.keys(product.specifications).length ? <table><tbody>{Object.entries(product.specifications).map(([key,value]) => <tr key={key}><th scope="row">{key}</th><td>{value}</td></tr>)}</tbody></table> : <p className="muted">Spesifikasi lengkap akan dikonfirmasi oleh tim sales.</p>}<Link to="/contact" className="store-button secondary"><MessageCircle size={17} /> Konsultasi produk</Link></section>{related.length > 0 && <section className="related-products"><h2>Produk dalam kategori yang sama</h2><div className="product-grid home-products">{related.map(p => <ProductCard key={p.id} product={p} />)}</div></section>}</div>;
}
