import { Link } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, ChevronRight, ShieldCheck, Truck, Headphones, ClipboardList } from 'lucide-react';
import { useFeaturedProducts } from '@/hooks/useCatalog';
import { categories } from '@/lib/store';
import { categoryIcons, CatalogState, ProductCard } from '@/components/store/StoreUI';
import hero from '@/assets/hero-industrial.jpg';
import { formPages } from '@/lib/site-pages';

export default function StoreHome() {
  const catalog = useFeaturedProducts();
  const products = catalog.data ?? [], loading = catalog.isLoading, error = catalog.isError;
  return <>
    <section className="store-container home-top"><aside className="category-sidebar"><h2>Belanja berdasarkan kategori</h2>{categories.map((category,i) => { const Icon = categoryIcons[i]; return <Link to={`/products?category=${encodeURIComponent(category)}`} key={category}><Icon size={19} /><span>{category}</span><ChevronRight size={14} /></Link>; })}<Link to="/products" className="all-categories">Lihat seluruh katalog <ArrowRight size={15} /></Link></aside>
      <div className="store-hero" style={{ backgroundImage: `linear-gradient(90deg, rgba(20,32,38,.97), rgba(20,32,38,.65)), url(${hero})` }}><div className="hero-copy"><span className="eyebrow light">BUILT FOR YOUR INDUSTRY</span><h1>Pengadaan elektrikal.<br /><em>Dan mekanikal.</em></h1><p>Dari komponen elektrikal hingga mekanikal.<br />Temukan solusi yang tepat untuk menjaga bisnis Anda terus bergerak.</p><Link className="store-button" to="/products">Jelajahi produk <ArrowRight size={17} /></Link><div className="hero-foot"><span>SEJAK <strong>2003</strong></span><span>Pengadaan lebih mudah.<br />Dengan partner yang memahami Anda.</span></div></div></div>
      <aside className="quote-promo"><ClipboardList size={30} strokeWidth={1.3} /><span className="eyebrow">UNTUK BISNIS ANDA</span><h2>Banyak kebutuhan,<br />satu penawaran.</h2><p>Susun daftar produk dan dapatkan penawaran sesuai kebutuhan proyek Anda.</p><Link to="/cart">Buat permintaan <ArrowUpRight size={18} /></Link><div className="quote-promo-note">Butuh barang khusus?<br /><Link to="/contact">Konsultasikan dengan tim kami →</Link></div></aside>
    </section>
    <div className="store-container benefits-strip">{[[ShieldCheck,'Produk terpercaya','Keaslian & kualitas diutamakan'],[Truck,'Pengiriman fleksibel','Sesuai kebutuhan pengadaan'],[Headphones,'Dukungan teknis','Bantu temukan produk yang tepat'],[ClipboardList,'Pengadaan B2B','Penawaran untuk bisnis Anda']].map(([Icon,title,desc]) => { const Mark = Icon as typeof ShieldCheck; return <div key={String(title)}><Mark size={26} strokeWidth={1.4} /><span><strong>{String(title)}</strong><small>{String(desc)}</small></span></div>; })}</div>
    <section className="catalog-section"><div className="store-container"><div className="section-heading"><div><span className="eyebrow">PILIHAN UNTUK OPERASIONAL ANDA</span><h2>Temukan komponen yang tepat</h2></div><Link to="/products">Lihat semua produk <ArrowRight size={16} /></Link></div><CatalogState loading={loading} error={error} reload={() => void catalog.refetch()} />{!loading && !error && (products.length ? <div className="product-grid home-products">{products.map(product => <ProductCard key={product.id} product={product} />)}</div> : <div className="empty-state"><h3>Katalog sedang dipersiapkan</h3><p>Tim sales siap membantu kebutuhan produk Anda.</p><Link to="/contact" className="store-button">Hubungi sales</Link></div>)}</div></section>
    <section className="store-container category-section"><div className="section-heading"><div><span className="eyebrow">SATU PARTNER, BERAGAM SOLUSI</span><h2>Untuk setiap kebutuhan industri</h2></div></div><div className="category-grid">{categories.map((name,i) => { const Icon = categoryIcons[i]; return <Link key={name} to={`/products?category=${encodeURIComponent(name)}`}><span className="category-number">0{i+1}</span><Icon size={36} strokeWidth={1.2} /><strong>{name}</strong><ArrowUpRight size={17} /></Link>; })}</div></section>
    <section className="store-container company-teaser"><div><span className="eyebrow">PRIMA PUTRA PERKASA</span><h2>Lebih dari supplier.<br />Partner industri Anda.</h2><p>Sejak 2003, kami membantu industri manufaktur dan kontraktor memenuhi kebutuhan elektrikal dan mekanikal, termasuk barang custom dan komponen yang sulit ditemukan.</p><Link to="/about" className="store-button secondary">Kenali kami lebih dekat <ArrowUpRight size={17} /></Link></div><div className="company-stat"><strong>20<span>+</span></strong><p>Tahun pengalaman<br />mendukung industri Indonesia</p><div className="stat-line" /></div></section>
    <section className="store-container service-home"><div className="section-heading"><div><span className="eyebrow">LAYANAN UNTUK BISNIS ANDA</span><h2>Satu partner, dari awal pengadaan.</h2></div><Link to="/help">Bantuan & panduan <ArrowRight size={16} /></Link></div><div className="home-service-grid">{formPages.map((page, i) => <Link key={page.slug} to={`/forms/${page.slug}`}><span>0{i + 1}</span><h3>{page.title}</h3><p>{page.intro}</p><ArrowUpRight size={19} /></Link>)}</div></section>
  </>;
}
